conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'parish/create/$', ParishCreateView.as_view(), name='parish_create'),
     url(r'parish/list/$', ParishListView.as_view(), name='parish_list'),
     url(r'parish/(?P<pk>[\w]+)/$', ParishUpdateView.as_view(), name='parish_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),

     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls
from dashboard.members import urls as member_insights_urls
from dashboard.members.views import *

from dashboard.views import *
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^insights/', include(member_insights_urls, namespace='dashboard')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^a_dashboard/$', AnalyticalDashboard.as_view(), name='a_dashboard'),
    url(r'^a_dashboard/get_members_per_month/$', get_members_per_month, name='get_members_per_month'),
    url(r'^a_dashboard/gender_distribution/$', gender_distribution, name='gender_distribution'),
    url(r'^a_dashboard/order_distribution/$', order_distribution, name='order_distribution'),
    url(r'^a_dashboard/get_orders_per_month/$', get_orders_per_month, name='get_orders_per_month'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'member-dashboard/$', MemberAnalyticalDashboard.as_view(), name='member_dashboard'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.conf.urls import url

from userprofile.views.authentication import *
from userprofile.views.user_managment import *

urlpatterns = [
    url(r'access/group/list/$', AccessLevelGroupListView.as_view(), name='ag_list'),
     url(r'access/group/create/$', AccessLevelGroupCreateView.as_view(), name='ag_create'),
     url(r'access/group/(?P<pk>[\w]+)/$', AccessLevelGroupUpdateView.as_view(), name='ag_edit'),
     url(r'access/list/$', AccessLevelListView.as_view(), name='access_list'),
     url(r'access/create/$', AccessLevelCreateView.as_view(), name='access_create'),
     url(r'access/(?P<pk>[\w]+)/$', AccessLevelUpdateView.as_view(), name='access_edit'),
     url(r'group/list/$', GroupListView.as_view(), name='group_list'),
     url(r'group/create/$', GroupCreateView.as_view(), name='group_create'),
     url(r'group/(?P<pk>[\w]+)/$', GroupUpdateView.as_view(), name='group_edit'),
     url(r'password/change/$', ChangePasswordView.as_view(), name='password_edit'),
     url(r'password/change/(?P<pk>[\w]+)/$', AdminChangePasswordView.as_view(), name='admin_password_edit'),
     url(r'create/$', UserProfileCreateView.as_view(), name='user_create'),
     url(r'list/$', UserProfileListView.as_view(), name='user_list'),
     url(r'(?P<pk>[\w]+)/$', UserProfileCreateView.as_view(), name='user_edit'),
    ]

userprofile/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.dispatch import receiver
from datetime import datetime, date
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.contrib.auth.models import Group
from rest_framework.authtoken.models import Token
from conf.models import District


class AccessLevel(models.Model):
    name = models.CharField(max_length=15, unique=True)
    create_date = models.DateTimeField(auto_now=True)
    update_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'access_level'
    
    def __unicode__(self):
        return self.name
    

class AccessLevelGroup(models.Model):
    access_level = models.OneToOneField(AccessLevel, unique=True)
    group = models.ManyToManyField(Group)
    
    class Meta:
        db_table = 'access_levell_group'
    
    def __unicode__(self):
        return "%s" % self.access_level


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    sex = models.CharField('Sex', max_length=10, choices=(('Male', 'Male'), ('Female', 'Female')), null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    msisdn = models.CharField(max_length=12, unique=True, null=True, blank=True)
    date_recruited = models.DateField(null=True)
    nin = models.CharField(max_length=255,  null=True, blank=True)
    access_level = models.ForeignKey(AccessLevel, null=True, blank=True, on_delete=models.CASCADE)
    district = models.ManyToManyField(District, blank=True)
    supervisor = models.ForeignKey(User, null=True, blank=True, related_name="supervisor")
    is_locked = models.BooleanField(default=0)
    receive_sms_notifications = models.BooleanField(default=0)
    create_date = models.DateTimeField(auto_now=True)
    update_date = models.DateTimeField(auto_now_add=True)
 
    class Meta:
        db_table = 'user_profile'

    @property
    def age(self):
        if self.date_of_birth:
            m = date.today() - self.date_of_birth
            return m.days / 365
        return None
        
    def is_union(self):
        if self.access_level:
            if self.access_level.name.upper() == "UNION" or self.access_level.name.upper() == "AGENT":
                return True
        if self.user.is_superuser:
            return True
        return False
    
    def is_cooperative(self):
        if self.access_level:
            if self.access_level.name.upper() == "COOPERATIVE":
                return True
        if self.user.is_superuser:
            return True
        return False
    
    def is_partner(self):
        if self.access_level:
            if self.access_level.name.upper() == "PARTNER":
                return True
        if self.user.is_superuser:
            return True
        return False
    
    def is_union_admin(self):
        if self.access_level.name.upper() == "UNION" or self.user.is_superuser:
            return True
        return False

    def __str__(self):
        return self.user.get_full_name()
        

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        Token.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()                           
                                    

userprofile/views/authentication.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, ListView, RedirectView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.models import Group
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm

from conf.utils import log_error, log_debug
from userprofile.models import *
from userprofile.forms import GroupForm, AccessLevelForm, AccessLevelGroupForm, LoginForm
from coop.models import Cooperative
from coop.utils import check_coop_url


class GroupCreateView(CreateView):
    model = Group
    # template_name = "conf/group_form.html"
    form_class = GroupForm
    success_url = reverse_lazy('profile:group_list')


class GroupUpdateView(UpdateView):
    model = Group
    # template_name = "conf/group_form.html"
    form_class = GroupForm
    success_url = reverse_lazy('conf:group_list')


class GroupListView(ListView):
    model = Group


class AccessLevelListView(ListView):
    model = AccessLevel


class AccessLevelCreateView(CreateView):
    model = AccessLevel
    form_class = AccessLevelForm
    success_url = reverse_lazy('profile:access_list')


class AccessLevelUpdateView(UpdateView):
    model = AccessLevel
    form_class = AccessLevelForm
    success_url = reverse_lazy('profile:access_list')


class AccessLevelGroupListView(ListView):
    model = AccessLevelGroup


class AccessLevelGroupCreateView(CreateView):
    model = AccessLevelGroup
    form_class = AccessLevelGroupForm
    success_url = reverse_lazy('profile:ag_list')


class AccessLevelGroupUpdateView(UpdateView):
    model = AccessLevelGroup
    form_class = AccessLevelGroupForm
    success_url = reverse_lazy('profile:ag_list')


class ChangePasswordView(View):
    template_name = 'userprofile/change_password.html'

    def get(self, request, *args, **kwargs):
        form = PasswordChangeForm(request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            password = form.cleaned_data.get('new_password2')
            check = password_log(request.user, password)
            if check:
                user = form.save()
                data = {
                    'title': 'Password Change',
                    'status_message': 'Your Password has been updated successfully.'
                }
                messages.success(request, 'Password Updated successfully')
                return render(request, 'account/status.html', data)
            messages.error(request,
                           'Sorry password Denied. Please use a password different from your previous %s passwords' % system_settings.password_reuse_threshold)
        return render(request, self.template_name, {'form': form})


class AdminChangePasswordView(View):
    template_name = 'userprofile/change_password.html'

    def get(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        user = User.objects.get(pk=pk)
        form = SetPasswordForm(user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        __user = User.objects.get(pk=pk)
        form = SetPasswordForm(__user, request.POST)

        if form.is_valid():
            user = form.save()
            data = {
                'title': 'Password Change',
                'status_message': 'Your Password has been updated successfully.'
            }
            messages.success(request, 'Password Updated successfully')
            return redirect('profile:user_list')
            # messages.success(request, 'Password Updated successfully')
            # return render(request, 'account/status.html', data)
            # return redirect('profile:user_list')
            # messages.error(request, 'Sorry password Denied. Please use a password different from your previous %s passwords' % system_settings.password_reuse_threshold)
        return render(request, self.template_name, {'form': form})


class LoginView(View):
    template_name = "userprofile/login.html"

    def get(self, request, *args, **kwargs):
        data = dict()
        log_debug('Login Page')
        data["form"] = LoginForm
        host = request.get_host()
        coop = check_coop_url(host)
        if coop:
            data["coop"] = coop
        return render(request, self.template_name, data)

    def post(self, request, *args, **kwargs):
        data = dict()
        form = LoginForm(request.POST)
        cooperative = False
        right_cooperative = None
        host = request.get_host()
        coop = check_coop_url(host)
        try:
            if form.is_valid():
                # set_login_attempt(request)
                username = form.cleaned_data.get('username', '')
                password = form.cleaned_data.get('password', '')

                user = authenticate(username=username, password=password)
                if user:
                    if user.is_active:

                        if user.profile.access_level or user.is_superuser:

                            if hasattr(user.profile.access_level, 'name'):
                                if user.profile.access_level.name.lower() == "cooperative" and user.cooperative_admin:
                                    cooperative = True
                                if coop:
                                    right_cooperative = "False"
                                    if coop == user.cooperative_admin.cooperative:
                                        right_cooperative = "True"
                            if cooperative or user.profile.is_union() or user.profile.is_partner():
                                print(right_cooperative)
                                print(cooperative)
                                if cooperative:
                                    if not right_cooperative:
                                        login(request, user)
                                        return redirect('dashboard')
                                    if right_cooperative == "True":
                                        login(request, user)
                                        return redirect('dashboard')
                                    if right_cooperative == "false":
                                        data['errors'] = "Cooperative not identified. Please contact the Admin"
                                elif user.profile.is_union() or user.profile.is_partner() or user.is_superuser:
                                    login(request, user)
                                    return redirect('dashboard')
                                else:
                                    data['errors'] = "Your Cooperative Credentials Failed. Please try again"
                            else:
                                data['errors'] = "Your Cooperative not identified. Please contact the Admin"
                        else:
                            data['errors'] = "You do not permission to Signin. Please contact the Admin"
                    else:
                        data['errors'] = "Your account is inactive"
                else:
                    data['errors'] = "Username or Password invalid"

        except Exception:
            data['errors'] = "Login Error. Contact Admin"
            log_error()
        return render(request, self.template_name, {'form': form, 'errors': data, 'active': ['staff_login', 'setting']})


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('login')
        # return super(LogoutView, self).get(request, *args, **kwargs)

userprofile/templates/userprofile/accesslevel_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Access Level</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'profile:access_create' %}" class="md-btn md-btn-success uk-float-right">Add Access Level</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                       
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                
                                <td><a href="{% url 'profile:access_edit' item.id %}"  class="uk-float-right"><i class="md-icon material-icons">&#xE254;</i></a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>
{% endblock %}

userprofile/templates/userprofile/accesslevelgroup_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Access Group</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'profile:ag_create' %}" class="md-btn md-btn-success uk-float-right">Add AG</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Access</th>
                        <th>Group</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.access_level }}</td>
                                <td></td>
                                <td><a href="{% url 'profile:ag_edit' item.id %}">Edit</a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="md-fab-wrapper md-fab-in-card">
                <a class="md-fab md-fab-wave" href="#"><i class="material-icons">&#xE52E;</i></a>
            </div>
        </div>
    </div>
{% endblock %}

userprofile/templates/userprofile/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Change Password</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="POST" class="new-event-form" role="role" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=field input_group_add_on='<i class="uk-input-group-icon uk-icon-key"></i>' %}
                                    
                    </div>
                    
                </div>
                {% endfor %}
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

userprofile/templates/userprofile/profile_form.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 
{% block style %}
    <!-- additional styles for plugins -->
    <!-- dropify -->
    <link rel="stylesheet" href="{% static 'assets/skins/dropify/css/dropify.css' %}">
    <!-- additional styles for plugins -->
    <!-- kendo UI -->
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.common-material.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.material.min.css' %}"/>
    <style>
        #id_common_animal_deseases{height: auto !important; min-height: 0px !important;}
    </style>
{% endblock %}

{% block page_content %}
<h3 class="heading_b uk-margin-bottom">System User</h3>
   <div class="md-card">
        <div class="md-card-content">
            {% if user_form.errors or  profile_form.errors or errors %}
                <div class="uk-alert uk-alert-danger" data-uk-alert="">
                   <a href="#" class="uk-alert-close uk-close"></a>
                   {% if user_form.non_field_errors %}
                    {{ user_form.non_field_errors }}
                   {% elif user_form.errors %}
                   {{ user_form.errors }}
                   {% elif profile_form.non_field_errors %}
                   {{ profile_form.non_field_errors }}
                   {% elif profile_form.errors %}
                   {{profile_form.errors}}
                   {% elif errors %}
                   {{ errors }}
                   {% endif %}
               </div>
            {% endif %}
            
            <form method="POST" class="new-event-form" role="role" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=user_form.username input_group_add_on='<i class="uk-input-group-icon uk-icon-key"></i>' %}
                        {% include "form/field.html" with field=user_form.password input_group_add_on='<i class="uk-input-group-icon uk-icon-lock"></i>' %}
                        {% include "form/field.html" with field=user_form.confirm_password input_group_add_on='<i class="uk-input-group-icon uk-icon-lock"></i>' %}
                        {% include "form/field.html" with field=user_form.is_active input_is_checkbox='True' %}
                        {% include "form/field.html" with field=user_form.is_superuser input_is_checkbox='True' %}
                                   
                    </div>
                    <div class="uk-width-medium-1-2">
                        {% include "form/field.html" with field=user_form.first_name input_group_add_on='<i class="uk-input-group-icon uk-icon-user-plus"></i>' %}
                        {% include "form/field.html" with field=user_form.last_name input_group_add_on='<i class="uk-input-group-icon uk-icon-user-plus"></i>' %}
                        {% include "form/field.html" with field=profile_form.sex input_group_add_on='<i class="uk-input-group-icon uk-icon-sex"></i>' %}
                        {% include "form/field.html" with field=profile_form.date_of_birth input_group_add_on='<i class="uk-input-group-icon uk-icon-calender"></i>' %}
                        {% include "form/field.html" with field=profile_form.date_recruited input_group_add_on='<i class="uk-input-group-icon uk-icon-calender"></i>' %}
                        {% include "form/field.html" with field=profile_form.msisdn input_group_add_on='<i class="uk-input-group-icon uk-icon-phone"></i>' %}
                        {% include "form/field.html" with field=user_form.email  input_group_add_on='<i class="uk-input-group-icon uk-icon-envelope"></i>' %}
                        {% include "form/field.html" with field=profile_form.access_level  input_group_add_on='<i class="uk-input-group-icon uk-icon-level-up"></i>' %}
                        {% include "form/field.html" with field=coop_form.cooperative  input_group_add_on='<i class="uk-input-group-icon uk-icon-level-up"></i>' %}
                        {% include "form/field.html" with field=profile_form.other_cooperative  input_group_add_on='<i class="uk-input-group-icon uk-icon-level-up"></i>' %}
                    </div>
                </div>
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block page_specific_scripts %}
 <!--  forms advanced functions -->

<script src="{% static 'assets/js/pages/forms_advanced.min.js' %}"></script>

   <script src="{% static 'bower_components/jquery.formset.js' %}"></script>

    <!-- kendo UI -->
    <script src="{% static 'assets/js/kendoui_custom.min.js' %}"></script>

    <!--  kendoui functions -->
    <script src="{% static 'assets/js/pages/kendoui.min.js' %}"></script>

<script>
   UIkit.datepicker("#id_date_of_birth", {maxDate:get_current_date(), format:'YYYY-MM-DD' });
   UIkit.datepicker("#id_date_recruited", {maxDate:get_current_date(), format:'YYYY-MM-DD' });
    function get_current_date(){
            var fullDate = new Date()
            console.log(fullDate);
            //Thu May 19 2011 17:25:38 GMT+1000 {}

            //convert month to 2 digits
            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : (fullDate.getMonth()+1);

            var currentDate = fullDate.getFullYear() + "-" + twoDigitMonth + "-" + (fullDate.getDate()+1);
            console.log(currentDate);
            return currentDate;
         }
    $("#selec_adv_1").selectize({
        plugins:{remove_button:{label:""}},
    })
</script>
{% endblock %}

userprofile/templates/userprofile/profile_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Users</h4>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'profile:user_create' %}" class="md-btn md-btn-success uk-float-right">Add User</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <!--<div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-1-2 uk-float-right">
                    <div class="uk-input-group">
                        <div class="md-input-wrapper"><label>Search</label><input type="text" class="md-input"><span class="md-input-bar"></span></div>
                        <span class="uk-input-group-addon">
                            <a href="#"><i class="uk-icon-search uk-icon-small"></i></a>
                        </span>
                    </div>
                </div>
            <hr>
            </div>-->
            
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Msisdn</th>
                        <th>Active</th>
                        <th>Super User</th>
                        <th>Access Level</th>
                        <th>Create Date</th>
                        <th>.</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.user.username }}</td>
                                <td>{{ item.user.email }}</td>
                                <td>{{ item.msisdn }}</td>
                                <td>{{ item.user.is_active }}</td>
                                <td>{{ item.user.is_superuser }}</td>
                                <td>{{ item.access_level }}</td>
                                <td>{{ item.user.date_joined }}</td>
                                
                                <td><a href="{% url 'profile:user_edit' item.user.id %}">Edit</a></td>
                                <td><a href="{% url 'profile:admin_password_edit' item.user.id %}">Password</a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}