conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'parish/create/$', ParishCreateView.as_view(), name='parish_create'),
     url(r'parish/list/$', ParishListView.as_view(), name='parish_list'),
     url(r'parish/(?P<pk>[\w]+)/$', ParishUpdateView.as_view(), name='parish_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),

     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

product/urls.py
from django.conf.urls import url

from product.views import *

urlpatterns = [
      url(r'item/price/(?P<pk>[\w]+)/$', get_item_price, name='item_price'),
      url(r'item/edit/(?P<pk>[\w]+)/$', ItemUpdateView.as_view(), name='item_update'),
      url(r'item/list/$', ItemListView.as_view(), name='item_list'),
      url(r'item/create/$', ItemCreateView.as_view(), name='item_create'),
      url(r'supplier/edit/(?P<pk>[\w]+)/$', SupplierUpdateView.as_view(), name='supplier_update'),
      url(r'supplier/list/$', SupplierListView.as_view(), name='supplier_list'),
      url(r'supplier/create/$', SupplierCreateView.as_view(), name='supplier_create'),
         
      url(r'price/log/(?P<pk>[\w]+)/$', ProductVariationPriceLogListView.as_view(), name='price_log_list'),
      url(r'price/request/(?P<pk>[\w]+)/$', get_product_price, name='product_price'),
      url(r'price/list/$', ProductVariationPriceListView.as_view(), name='price_list'),
      url(r'price/create/$', ProductVariationPriceCreateView.as_view(), name='price_create'),
      url(r'price/(?P<pk>[\w]+)/$', ProductVariationPriceUpdateView.as_view(), name='price_edit'),
      url(r'variation/list/$', ProductVariationListView.as_view(), name='variation_list'),
      url(r'variation/create/$', ProductVariationView.as_view(), name='variation_create'),
      url(r'variation/(?P<pk>[\w]+)/$', ProductVariationView.as_view(), name='variation_edit'),
      url(r'unit/list/$', ProductUnitListView.as_view(), name='unit_list'),
      url(r'unit/create/$', ProductUnitCreateView.as_view(), name='unit_create'),
      url(r'unit/(?P<pk>[\w]+)/$', ProductUnitUpdateView.as_view(), name='unit_edit'),

      url(r'offtaker/list/$', OffTakerListView.as_view(), name='offtaker_list'),
      url(r'offtaker/create/$', OffTakerCreateView.as_view(), name='offtaker_create'),
      url(r'offtaker/(?P<pk>[\w]+)/$', OffTakerUpdateView.as_view(), name='offtaker_edit'),

      url(r'offtaker/sale/list/$', OffTakerSaleListView.as_view(), name='offtaker_sale_list'),
      url(r'offtaker/sale/create/$', OffTakerSaleCreateView.as_view(), name='offtaker_sale_create'),
      url(r'offtaker/sale/(?P<pk>[\w]+)/$', OffTakerSaleUpdateView.as_view(), name='offtaker_sale_edit'),
]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls
from dashboard.members import urls as member_insights_urls
from dashboard.members.views import *

from dashboard.views import *
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^insights/', include(member_insights_urls, namespace='dashboard')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^a_dashboard/$', AnalyticalDashboard.as_view(), name='a_dashboard'),
    url(r'^a_dashboard/get_members_per_month/$', get_members_per_month, name='get_members_per_month'),
    url(r'^a_dashboard/gender_distribution/$', gender_distribution, name='gender_distribution'),
    url(r'^a_dashboard/order_distribution/$', order_distribution, name='order_distribution'),
    url(r'^a_dashboard/get_orders_per_month/$', get_orders_per_month, name='get_orders_per_month'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'member-dashboard/$', MemberAnalyticalDashboard.as_view(), name='member_dashboard'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=25, unique=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product'
    
    def product_variation(self):
        return ProductVariation.objects.filter(product=self)
    
    
    def __unicode__(self):
        return self.name
    

class ProductUnit(models.Model):
    name = models.CharField(max_length=25, unique=True)
    code = models.CharField(max_length=3, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_units'
        verbose_name = 'Product Unit'
        verbose_name_plural = 'Product Units'
        
    
    def __unicode__(self):
        return self.name
    

class ProductVariation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    unit = models.ForeignKey(ProductUnit, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation'
        verbose_name = 'Product'
        verbose_name_plural = 'Product'
        unique_together = ['product', 'name']
           
    def __unicode__(self):
        return self.name

    def get_price(self):
        try:
            prod = ProductVariationPrice.objects.get(product=self)
            return prod.price
        except Exception as e:
            return 0
    

class ProductVariationPrice(models.Model):
    product = models.ForeignKey(ProductVariation, related_name='variation_price', on_delete=models.CASCADE)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation_price'
        verbose_name = 'Product Price'
        verbose_name_plural = 'Product Prices'
        unique_together = ['product', 'unit']
        
    def __unicode__(self):
        return "%s" % self.product


class ProductVariationPriceLog(models.Model):
    product = models.ForeignKey(ProductVariation, on_delete=models.CASCADE)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'product_variation_price_log'
        verbose_name = 'Product Price'
        verbose_name_plural = 'Product Prices'
        
    def __unicode__(self):
        return "%s" % self.product
    
class Supplier(models.Model):
    name = models.CharField(max_length=255, unique=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'supplier'
        
    def __unicode__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=255, unique=True)
    category = models.CharField(max_length=255, null=True, blank=True)
    supplier = models.ForeignKey(Supplier, null=True, blank=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    unit = models.ForeignKey(ProductUnit, null=True, blank=True, on_delete=models.SET_NULL)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'item'
        
    def __unicode__(self):
        return self.name


class ItemCategory(models.Model):
    name = models.CharField(max_length=255)
    
# @receiver(post_save, sender=ProductVariationPrice)
# def create_price_log(sender, instance, created, **kwargs):
#     if created:
#         ProductVariationPriceLog.objects.create(variation=instance)

@receiver(post_save, sender=ProductVariationPrice)
def save_price_log(sender, instance, **kwargs):
    ProductVariationPriceLog.objects.create(product=instance.product,
                                            price=instance.price,
                                            unit=instance.unit,
                                            created_by=instance.created_by)


class OffTaker(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255, null=True, blank=True)
    created_by = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'off_taker'

    def __unicode__(self):
        return "%s" % self.name or u''


class OffTakerSale(models.Model):
    off_taker = models.ForeignKey(OffTaker, on_delete=models.CASCADE)
    product = models.ForeignKey(ProductVariation, on_delete=models.CASCADE )
    unit_price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.DecimalField(max_digits=9, decimal_places=2)
    total_price = models.DecimalField(max_digits=9, decimal_places=2)
    created_by = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'off_taker_sale'

    def __unicode__(self):
        return "%s" % self.name or u''

product/forms.py
from django import forms

from conf.utils import bootstrapify
from product.models import *

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name']


class ProductUnitForm(forms.ModelForm):
    class Meta:
        model = ProductUnit
        fields = ['name', 'code']
        
        
class ProductVariationForm(forms.ModelForm):
    class Meta:
        model = ProductVariation
        fields = ['name', 'unit']


class ProductVariationPriceForm(forms.ModelForm):
    class Meta:
        model = ProductVariationPrice
        fields = ['product', 'unit', 'price']
        
class SupplierForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = ['name']
        
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ['create_date', 'update_date']


class ItemSearchForm(forms.Form):
    item = forms.CharField(max_length=150, required=False)
    category = forms.CharField(max_length=150, required=False)
    supplier = forms.CharField(max_length=150, required=False)


class OffTakerForm(forms.ModelForm):
    class Meta:
        model = OffTaker
        exclude = ['create_date', 'update_date']


class OffTakerSaleForm(forms.ModelForm):
    class Meta:
        model = OffTakerSale
        exclude = ['create_date', 'update_date']

       
bootstrapify(ItemSearchForm)
bootstrapify(SupplierForm)
bootstrapify(ItemForm)
bootstrapify(ProductForm)
bootstrapify(ProductUnitForm)
bootstrapify(ProductVariationForm)
bootstrapify(ProductVariationPriceForm)
bootstrapify(OffTakerForm)
bootstrapify(OffTakerSaleForm)

product/templates/product/item_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Item List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:item_create' %}" class="md-btn md-btn-success uk-float-right">Add Item</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <form method="GET" class="new-event-form" role="role">
                    <div class="uk-grid" data-uk-grid-margin>
                    {% for field in form %}
                        <div class="uk-width-medium-1-2">
                            {% include "form/field.html" with field=field %}
                        </div>
                    {% endfor %}
                    </div>
                    <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Search</button>
                        <a href="{% url 'product:item_list' %}" type="submit" class="md-btn md-btn-primary">Refresh</a>
                        <a href="{% url 'product:item_list' %}?download=True" type="submit" class="md-btn md-btn-primary">Download</a>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Supplier</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.category }}</td>
                                <td>{{ item.supplier }}</td>
                                <td>{{ item.price }}</td>
                                
                                <td>
                                    <a href="{% url 'product:item_update' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/offtaker_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Offtaker List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:offtaker_create' %}" class="md-btn md-btn-success uk-float-right">Add Offtaker</a>
            <a href="{% url 'product:offtaker_sale_list' %}" class="md-btn md-btn-success uk-float-right">Add Sale</a>
        </div>
    </div>
<!--    <div class="md-card uk-margin-medium-bottom">-->
<!--        <div class="md-card-content">-->
<!--            <div class="uk-overflow-container">-->
<!--                <form method="GET" class="new-event-form" role="role">-->
<!--                    <div class="uk-grid" data-uk-grid-margin>-->
<!--                    {% for field in form %}-->
<!--                        <div class="uk-width-medium-1-2">-->
<!--                            {% include "form/field.html" with field=field %}-->
<!--                        </div>-->
<!--                    {% endfor %}-->
<!--                    </div>-->
<!--                    <div class="uk-grid">-->
<!--                    <div class="uk-width-1-1">-->
<!--                        <button type="submit" class="md-btn md-btn-success">Search</button>-->
<!--                        <a href="{% url 'product:item_list' %}" type="submit" class="md-btn md-btn-primary">Refresh</a>-->
<!--                        <a href="{% url 'product:item_list' %}?download=True" type="submit" class="md-btn md-btn-primary">Download</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--                </form>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.address }}</td>
                                
                                <td>
                                    <a href="{% url 'product:offtaker_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/offtakersale_form.html
{% extends 'base.html' %}
{% load static %}
{% load my_custom_tags %} 

{% block style %}
    <!-- additional styles for plugins -->
    <!-- dropify -->
    <link rel="stylesheet" href="{% static 'assets/skins/dropify/css/dropify.css' %}">
    
{% endblock %}
{% block page_content %}
<h3 class="heading_b uk-margin-bottom">Offtaker Sale Form</h3>
   <div class="md-card">
        <div class="md-card-content">
            <form method="POST" class="new-event-form" role="role" enctype="multipart/form-data">
                {% csrf_token %}
                {% include "error_template.html" with form=form %}
                <div class="uk-grid" data-uk-grid-margin>
                    <div class="uk-width-medium-1-2">
                        {% for field in form %}
                            {% include "form/field.html" with field=field input_group_add_on='<i class="uk-input-group-icon uk-icon-institution "></i>' %}
                        {% endfor%}
                    </div>

                </div>
                <div class="uk-grid">
                    <div class="uk-width-1-1">
                        <button type="submit" class="md-btn md-btn-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- page specific plugins -->
    <!-- ionrangeslider -->
    <script src="{% static 'bower_components/ion.rangeslider/js/ion.rangeSlider.min.js' %}"></script>

    <!--  forms advanced functions -->
    <script src="{% static 'assets/js/pages/forms_advanced.min.js' %}"></script>
    

    
    <script>

        $("#id_quantity").on('input', function() {
            var unit_price = $("#id_unit_price").val();
            var quantity = $("#id_quantity").val();
            var total = quantity * unit_price
            $("#id_total_price").val(total);

        });
    </script>
{% endblock %}

product/templates/product/offtakersale_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Offtaker Sale List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:offtaker_sale_create' %}" class="md-btn md-btn-success uk-float-right">Add Offtaker Sale</a>
        </div>
    </div>
<!--    <div class="md-card uk-margin-medium-bottom">-->
<!--        <div class="md-card-content">-->
<!--            <div class="uk-overflow-container">-->
<!--                <form method="GET" class="new-event-form" role="role">-->
<!--                    <div class="uk-grid" data-uk-grid-margin>-->
<!--                    {% for field in form %}-->
<!--                        <div class="uk-width-medium-1-2">-->
<!--                            {% include "form/field.html" with field=field %}-->
<!--                        </div>-->
<!--                    {% endfor %}-->
<!--                    </div>-->
<!--                    <div class="uk-grid">-->
<!--                    <div class="uk-width-1-1">-->
<!--                        <button type="submit" class="md-btn md-btn-success">Search</button>-->
<!--                        <a href="{% url 'product:item_list' %}" type="submit" class="md-btn md-btn-primary">Refresh</a>-->
<!--                        <a href="{% url 'product:item_list' %}?download=True" type="submit" class="md-btn md-btn-primary">Download</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--                </form>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Off Taker</th>
                        <th>Product</th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total Price</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.off_taker }}</td>
                                <td>{{ item.product }}</td>
                                <td>{{ item.unit_price }}</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.total_price }}</td>

                                <td>
                                    <a href="{% url 'product:offtaker_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productunit_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product Unit List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:unit_create' %}" class="md-btn md-btn-success uk-float-right">Add Product Unit</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                       
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                
                                <td>
                                    <a href="{% url 'product:unit_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                    <a href="{% url 'product:unit_edit' item.id %}" class="md-btn md-btn-primary md-btn-wave waves-effect waves-button uk-float-right">Detail</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariation_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:variation_create' %}" class="md-btn md-btn-success uk-float-right">Add Product</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Type</th>
                        <th>Product</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>
                                   
                                    {% for variation in item.product_variation %}
                                        <div><strong>- {{ variation }}</strong><div>
                                    {% endfor %}
                                
                                </td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   <a href="{% url 'product:variation_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Edit</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/productvariationprice_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Product Price List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            <a href="{% url 'product:price_create' %}" class="md-btn md-btn-success uk-float-right">Add Price</a>
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Product</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.product }}</td>
                                <td>
                                  {{ item.price }} per {{ item.unit }}<div>
                                </td>
                                <td>
                                    <!--<a href="#"><i class="md-icon material-icons"></i></a>
                                    <a href="#"><i class="md-icon material-icons">detail</i></a>-->
                                   <a href="{% url 'product:price_edit' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Adjust</a>
                                   <a href="{% url 'product:price_log_list' item.product.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right"><i class="md-icon material-icons"></i>Price Log</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}