conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'parish/create/$', ParishCreateView.as_view(), name='parish_create'),
     url(r'parish/list/$', ParishListView.as_view(), name='parish_list'),
     url(r'parish/(?P<pk>[\w]+)/$', ParishUpdateView.as_view(), name='parish_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),

     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

payment/urls.py
from django.conf.urls import url

from payment.views import *

urlpatterns = [
    
    url(r'bulk/delete/(?P<pk>[\w]+)/$', BulkPaymentDelete.as_view(), name='bulk_delete'),
    url(r'bulk/confirm/(?P<pk>[\w]+)/$', BulkPaymentConfirm.as_view(), name='bulk_confirm'),
    url(r'bulk/detail/(?P<pk>[\w]+)/$', BulkPaymentDetail.as_view(), name='bulk_detail'),
    url(r'bulk/list/$', BulkPaymentListView.as_view(), name='bulk_list'),
    url(r'bulk/upload/$', BulkPaymentView.as_view(), name='upload'),
    url(r'edit/(?P<pk>[\w]+)/$', PaymentMethodUpateView.as_view(), name='update'),
    url(r'detail/(?P<pk>[\w]+)/$', PaymentTransactionDetail.as_view(), name='detail'),
    url(r'upload/$', UploadPaymentView.as_view(), name='upload'),
    url(r'dowload/$', DownloadPaymentExcelView.as_view(), name='download'),
    url(r'list/$', PaymentMethodListView.as_view(), name='list'),
    url(r'create/$', PaymentTransactionCreateView.as_view(), name='create')
]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls
from dashboard.members import urls as member_insights_urls
from dashboard.members.views import *

from dashboard.views import *
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^insights/', include(member_insights_urls, namespace='dashboard')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^a_dashboard/$', AnalyticalDashboard.as_view(), name='a_dashboard'),
    url(r'^a_dashboard/get_members_per_month/$', get_members_per_month, name='get_members_per_month'),
    url(r'^a_dashboard/gender_distribution/$', gender_distribution, name='gender_distribution'),
    url(r'^a_dashboard/order_distribution/$', order_distribution, name='order_distribution'),
    url(r'^a_dashboard/get_orders_per_month/$', get_orders_per_month, name='get_orders_per_month'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'member-dashboard/$', MemberAnalyticalDashboard.as_view(), name='member_dashboard'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from coop.models import CooperativeMember, Cooperative, FarmerGroup

class PaymentAPI():
    pass


class BulkPaymentRequest(models.Model):
    file_name = models.CharField(max_length=255)
    cooperative = models.ForeignKey(Cooperative, blank=True, null=True, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=32, decimal_places=2)
    payment_method = models.CharField(max_length=18)
    status = models.CharField(max_length=10, choices=(('PROCESSING', 'PROCESSING'),
        ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')))
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_Date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "bulk_payment_request"
        
    def __unicode__(self):
        return self.status or u''
    
    def get_log(self):
        return BulkPaymentRequestLog.objects.filter(bulk_payment_request=self)
    
    
class BulkPaymentRequestLog(models.Model):
    bulk_payment_request = models.ForeignKey(BulkPaymentRequest, on_delete=models.CASCADE)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    payment_method = models.CharField(max_length=18)
    transaction_date = models.DateField()
    process_state = models.CharField(max_length=10, choices=(('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'),
        ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')))
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    create_Date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'bulk_payment_request_log'
        
    def __unicode__(self):
        return u''


class MemberPayment(models.Model):
    transaction_id = models.CharField(max_length=255)
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)
    payemnt_reference = models.CharField(max_length=255, blank=True,)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    payment_date = models.DateTimeField()
    payment_method = models.CharField(max_length=10, choices=(('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')))
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    status = models.CharField(max_length=15, choices=(('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')), blank=True)
    request = models.TextField(blank=True)
    response = models.TextField(blank=True)
    response_date = models.DateTimeField(blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "member_payment"
        
    def __unicode__(self):
        return self.payemnt_reference
    

class MobileMoneyRequest(models.Model):
    transaction_reference = models.CharField(max_length=255)
    phone_number = models.CharField(max_length=25)
    member = models.ForeignKey(CooperativeMember, blank=True, null=True, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    transaction_type = models.CharField(max_length=15, choices=(('COLLECTION', 'COLLECTION'), ('PAYOUT', 'PAYOUT')), blank=True)
    status = models.CharField(max_length=15, choices=(('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')), blank=True)
    request = models.TextField(blank=True)
    response = models.TextField(blank=True)
    response_reference = models.CharField(max_length=255, null=True, blank=True)
    response_date = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "mobile_money_request"
        
    def __unicode__(self):
        return self.phone_number
    
    
class MemberPaymentTransaction(models.Model):
    cooperative = models.ForeignKey(Cooperative, blank=True, null=True, on_delete=models.CASCADE)
    farmer_group = models.ForeignKey(FarmerGroup, blank=True, null=True, on_delete=models.CASCADE)
    member = models.ForeignKey(CooperativeMember, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255,  blank=True, null=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    payment_date = models.DateTimeField()
    transaction_reference = models.CharField(max_length=255)
    payment_method = models.CharField(max_length=16, choices=(('CASH', 'CASH'), ('BANK', 'BANK'), ('MOBILE MONEY', 'MOBILE MONEY')))
    status = models.CharField(max_length=15, choices=(('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('FAILED', 'FAILED')), blank=True)
    balance_before = models.DecimalField(max_digits=32, decimal_places=2, blank=True, null=True)
    amount = models.DecimalField(max_digits=32, decimal_places=2)
    balance_after = models.DecimalField(max_digits=32, decimal_places=2, blank=True, null=True)
    creator = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    transaction_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = "member_payment_transaction"
        
    def __unicode__(self):
        return "%s" % self.transaction_reference

    def get_mobile_money_transaction(self):
        mm_transaction = None
        trx = MobileMoneyRequest.objects.filter(transaction_reference=self.transaction_reference)
        if trx.exists():
            mm_transaction = trx[0]
        return mm_transaction

credit/forms.py
from django import forms
from django.contrib.auth.models import User
from credit.models import CreditManager, LoanRequest, LoanRepaymentTransaction
from conf.utils import bootstrapify, internationalize_number, PHONE_REGEX
from coop.models import CooperativeMember


class CreditManagerForm(forms.ModelForm):
    class Meta:
        model = CreditManager
        exclude = ['create_date', 'update_date']

class CreditManagerUserForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput)
    password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput)
    msisdn = forms.CharField(max_length=150)

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop("instance", None)
        print(instance)
        super(CreditManagerUserForm, self).__init__(*args, **kwargs)
        if instance:
            self.fields.pop('password')
            self.fields.pop('confirm_password')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'msisdn', 'is_active', 'username', 'password',
                  'confirm_password']


class LoanUploadForm(forms.Form):
    sheetChoice = (
        ('1', 'sheet1'),
        ('2', 'sheet2'),
        ('3', 'sheet3'),
        ('4', 'sheet4'),
        ('5', 'sheet5'),
    )

    rowchoices = (
        ('1', 'Row 1'),
        ('2', 'Row 2'),
        ('3', 'Row 3'),
        ('4', 'Row 4'),
        ('5', 'Row 5')
    )

    choices = list()
    for i in range(65, 91):
        choices.append([i - 65, chr(i)])

    excel_file = forms.FileField()
    credit_manager = forms.ModelChoiceField(queryset=CreditManager.objects.all())
    proceed = forms.BooleanField(label='Proceed if farmer is not found', required=False)
    sheet = forms.ChoiceField(label="Sheet", choices=sheetChoice, widget=forms.Select(attrs={'class': 'form-control'}))
    row = forms.ChoiceField(label="Row", choices=rowchoices, widget=forms.Select(attrs={'class': 'form-control'}))
    name_col = forms.ChoiceField(label='Name Column', initial=0, choices=choices,
                                 widget=forms.Select(attrs={'class': 'form-control'}),
                                 help_text='The column containing the Last Name')
    phone_number_col = forms.ChoiceField(label='Phone Number Column', initial=1, choices=choices,
                                       widget=forms.Select(attrs={'class': 'form-control'}),
                                       help_text='The column containing the Phone Number Name')
    request_date_col = forms.ChoiceField(label='Request Date Column', initial=2, choices=choices,
                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                      help_text='The column containing the Village')
    agent_col = forms.ChoiceField(label='Agent Column', initial=3, choices=choices,
                                        widget=forms.Select(attrs={'class': 'form-control'}),
                                        help_text='The column containing the Loan Agent')
    loan_amount_col = forms.ChoiceField(label='Loan Amount Column', initial=4, choices=choices,
                                     widget=forms.Select(attrs={'class': 'form-control'}),
                                     help_text='The column containing the Loan Amount')


class LoanSearchForm(forms.Form):
    search = forms.CharField(max_length=150, required=False)
    cooperative = forms.ChoiceField(widget=forms.Select(), choices=[], required=False)
    start_date = forms.CharField(max_length=150, required=False, widget=forms.TextInput(attrs={'id': 'uk_dp_start',
                                                                                               'data-uk-datepicker': "{format:'YYYY-MM-DD'}",
                                                                                               'autocomplete': "off"}))
    end_date = forms.CharField(max_length=150, required=False,
                               widget=forms.TextInput(attrs={'class': 'some_class', 'id': 'uk_dp_end',
                                                             'data-uk-datepicker': "{format:'YYYY-MM-DD'}",
                                                             'autocomplete': "off"}))
    status = forms.ChoiceField(widget=forms.Select(), required=False, choices=(('', '-----'), ('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'),
                                                      ('ACCEPTED', 'ACCEPTED'), ('NOT TAKEN', 'NOTTAKEN'),
                                                      ('INPROGRESS', 'INPROGRESS'), ('PAID', 'PAID'),
                                                      ('APPROVED', 'APPROVED')))

    def __init__(self,  *args, **kwargs):
        super(LoanSearchForm, self).__init__(*args, **kwargs)

        qs = LoanRequest.objects.values('member__cooperative__id', 'member__cooperative__name').distinct()
        print(qs)
        choices = [['', 'Cooperative']]
        for q in qs:
            choices.append([q['member__cooperative__id'], q['member__cooperative__name']])
        self.fields['cooperative'].choices = choices


class ApproveForm(forms.Form):
    amount = forms.IntegerField()
    supplier = forms.CharField(max_length=255)


class LoanRequestForm(forms.ModelForm):
    class Meta:
        model = LoanRequest
        exclude = ['create_date', 'update_date']

    def __init__(self, *args, **kwargs):
        super(LoanRequestForm, self).__init__(*args, **kwargs)
        self.fields['member'].queryset = CooperativeMember.objects.none()
        if self.instance.pk:
            cooperative = self.instance.member.id
            mbs = CooperativeMember.objects.filter(pk=cooperative)
            self.fields['member'].queryset = mbs


class LoanRepaymentForm(forms.ModelForm):
    class Meta:
        model = LoanRepaymentTransaction
        exclude = ['create_date', 'update_date']

    def __init__(self, *args, **kwargs):
        super(LoanRepaymentForm, self).__init__(*args, **kwargs)



bootstrapify(LoanRepaymentForm)
bootstrapify(LoanRequestForm)
bootstrapify(ApproveForm)
bootstrapify(LoanSearchForm)
bootstrapify(LoanUploadForm)
bootstrapify(CreditManagerForm)
bootstrapify(CreditManagerUserForm)

payment/templates/payment/bulkpaymentrequest_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Payments</h4>
        </div>
        <div class="uk-width-medium-1-2 uk-text-right">
            <!--<a href="{% url 'payment:download' %}" class="md-btn md-btn-success ">Download Excel</a>-->
            <a href="{% url 'payment:list' %}" class="md-btn md-btn-success ">Payments</a>
            {% if request.user.profile.is_union %}
                <a href="{% url 'payment:upload' %}" class="md-btn md-btn-success ">Upload Excel</a>
                 
            {% endif %}
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Total Amount</th>
                        <th>Payment Method</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <!--<td>{{ item.payment_date| date:"d, M Y" }}</td>-->
                               
                                <td>{{ item.total_amount }}</td>
                                <td>{{ item.payment_method }}</td>
                                <td>{{ item.status }}</td>
                                <td>{{ item.update_date }}</td>
                                <td><a href="{% url 'payment:bulk_detail' item.id %}"  class="md-btn md-btn-success uk-margin-small-top uk-float-right">Detail</a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
           
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

payment/templates/payment/memberpaymenttransaction_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %}
{% load el_pagination_tags %}
{% block style %}
<style type="text/css">
    .row-pagination{
        margin: 15px;
    }
    .row-pagination a{
        padding: 10px;
        border-radius: 4px;
    }

    .endless_page_current{
        background: #7cb342;
        color: #fff;
        padding: 10px;
        border-radius: 4px;
    }

</style>
{% endblock %}

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h4 class="heading_a uk-margin-bottom">Payments</h4>
        </div>
        <div class="uk-width-medium-1-2 uk-text-right">
            <a href="#" id="download_excel" class="md-btn md-btn-primary ">Download Excel</a>
            <a href="{% url 'payment:upload' %}" class="md-btn md-btn-info ">Upload Payment</a>
            <a href="{% url 'payment:bulk_list' %}" class="md-btn md-btn-success ">Bulk Payment</a>
            {% if request.user.profile.is_union %}
                 <a href="{% url 'payment:create' %}" class="md-btn md-btn-success ">Add Payment</a>
            {% endif %}
        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <form class="" method="get">
            <div class="uk-grid" data-uk-grid-margin>
                {% for field in form %}
                    <div class="uk-width-medium-1-5">
                        {% include 'form/field.html' with field=field %}
                    </div>
                {% endfor %}
            </div>
            <div class="uk-grid" data-uk-grid-margin>
                <div class="uk-width-medium-5 uk-right">
                </div>
                <div class="uk-width-medium-5 uk-float-right">
                    <button class="md-btn" name="_search" > Search </button>
                    <a href="." class="md-btn md-btn-small md-btn-flat md-btn-flat-primary  uk-margin-small-left"><i class="material-icons md-24 " title="Delete">refresh</i></a>
                    <!--<button class="md-btn md-btn-success uk-float-right" name="_download" value="download"> Export CSV </button>-->
                </div>
             </div>
            </form>
            </div>
        <hr class="uk-grid-divider">
        <div class="md-card-content">
            
            <div class="uk-overflow-container">
                <table id="dt_tableTools" class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Payment Date</th>
                        <th>Coop</th>
                        <th>Member</th>
                        <th>Recipient Name</th>
                        <th>Number</th>
                        <th>Amount</th>
                        <th>Reference</th>
                        <th>Status</th>
                        <th>Payment Method</th>
                        <th>Update Date</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% paginate object_list %}{% get_pages %}
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.payment_date| date:"d, M Y" }}</td>
                               <td>{{ item.cooperative|default:"-" }}</td>
                                <td>{{ item.member|default:"-" }}</td>
                                <td>{{ item.name }}</td>
                                <td>{{ item.member.phone_number|default:item.phone_number }}</td>
                                <td>{{ item.amount }}</td>
                                <td>{{ item.transaction_reference }}</td>
                                <td>{% include 'status_text.html' with field=item.status %}</td>
                                <td>{{ item.payment_method }}</td>
                                <td>{{ item.update_date }}</td>
                                <td><a href="{% url 'payment:detail' item.id %}" class="md-btn md-btn-success uk-margin-small-top uk-float-right" >Detail</a></td>
                            </tr>
                            
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row-pagination">
                Showing entries
                {{ pages.current_start_index }}-{{ pages.current_end_index }} of
                {{ pages.total_count }}.
                {# Just print pages to render the Digg-style pagination. #}
                {% show_pages %}
            </div>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
<script>
    $("#download_excel").on('click', function(e){
            var qstring = window.location.search.replace("?", "");
            var url = "{% url 'payment:download' %}"+"?download=csv&";
            //var urlParams = new URLSearchParams(window.location.search);
            var furl = url+qstring;
           
            window.location = furl
            //$.get(furl, function(data, status){
            //    alert("Data: " + data + "\nStatus: " + status);
            //});
            
        });
    $("#id_start_date").attr("autocomplete", "off");
    $("#id_end_date").attr("autocomplete", "off");
</script>
 <!-- datatables -->
    <script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
    <!-- datatables colVis-->
    <script src="{% static 'bower_components/datatables-colvis/js/dataTables.colVis.js' %}"></script>
<!-- datatables tableTools-->
    <script src="{% static 'bower_components/datatables-tabletools/js/dataTables.tableTools.js' %}"></script>
    <!-- datatables custom integration -->
    <script src="{% static 'assets/js/custom/datatables_uikit.min.js' %}"></script>

    <!--  datatables functions -->
    <script src="{% static 'assets/js/pages/plugins_datatables.min.js' %}"></script>
{% endblock %}

payment/templates/payment/paymentupload_form.html
{% extends 'base.html' %}
{% load static %}
{% load my_custom_tags %}

{% block style %}
    <!-- additional styles for plugins -->
     <!-- kendo UI -->
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.common-material.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'bower_components/kendo-ui/styles/kendo.material.min.css' %}"/>
    <style>
        .k-combobox{
            width: 100% !important;
        }
    </style>
    
{% endblock %}
{% block page_content %}
    <h3 class="heading_b uk-margin-bottom">{{ title|default:"Payment Form" }}</h3>
    <div class="md-card">
        <div class="md-card-content">
            <p class="uk-text-warning uk-text-bold uk-margin-remove">
                    Use the Collection Upload template <a href="{% static 'assets/template_files/payment_template_file.xlsx' %}">Here</a> to upload the Collection data
                </p>
            {{ help_text|default:"Upload excel file of member payment" }} <br><br><br>
            <form method="POST" class="new-event-form" role="role" enctype="multipart/form-data">
               {% csrf_token %}
               {% if error %}<div class="uk-alert uk-alert-danger" data-uk-alert="">{{ error.errors }}<div>{{ error }}</div> </div>{% endif %}
               {% include "error_template.html" with form=form %}
                <div class="uk-grid" data-uk-grid-margin="">
                    
                {% for field in form %}
                     <div class="uk-width-medium-1">
                         <div class="md-input-wrapper">
                             {% include "form/field.html" with field=field input_group_add_on='<i class="uk-input-group-icon uk-icon-building "></i>' %}
                         </div>
                     </div>
                {% endfor %}
                
                <div class="uk-grid uk-text-right" data-uk-grid-margin="">
                    <div class="uk-width-medium-1-1 uk-text-right">
                        <button href="#" id="id_submit" class="md-btn md-btn-primary uk-margin-small-top">SUBMIT</button>
                    </div>
                </div>
           </form>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
{% endblock %}
    