conf/urls.py
from django.conf.urls import url

from conf.views import *

urlpatterns = [
     url(r'sms/template/$', MessageTemplatesView.as_view(), name='sms_template'),
     url(r'district/list/$', DistrictListView.as_view(), name='district_list'),
     url(r'district/create/$', DistrictCreateView.as_view(), name='district_create'),
     url(r'district/(?P<pk>[\w]+)/$', DistrictUpdateView.as_view(), name='district_edit'),
     url(r'district/delete/(?P<pk>[\w]+)/$', DistrictDeleteView.as_view(), name='district_delete'),
     url(r'county/create/$', CountyCreateView.as_view(), name='county_create'),
     url(r'county/list/$', CountyListView.as_view(), name='county_list'),
     url(r'county/(?P<pk>[\w]+)/$', CountyUpdateView.as_view(), name='county_edit'),

     url(r'sc/create/$', SubCountyCreateView.as_view(), name='subcounty_create'),
     url(r'sc/list/$', SubCountyListView.as_view(), name='subcounty_list'),
     url(r'sc/(?P<pk>[\w]+)/$', SubCountyUpdateView.as_view(), name='subcounty_edit'),
     url(r'parish/create/$', ParishCreateView.as_view(), name='parish_create'),
     url(r'parish/list/$', ParishListView.as_view(), name='parish_list'),
     url(r'parish/(?P<pk>[\w]+)/$', ParishUpdateView.as_view(), name='parish_edit'),
     url(r'village/create/$', VillageCreateView.as_view(), name='village_create'),
     url(r'village/list/$', VillageListView.as_view(), name='village_list'),
     url(r'village/(?P<pk>[\w]+)/$', VillageUpdateView.as_view(), name='village_edit'),
     url(r'payment/create/$', PaymentModeCreateView.as_view(), name='payment_create'),
     url(r'payment/list/$', PaymentModeListView.as_view(), name='payment_list'),
     url(r'payment/(?P<pk>[\w]+)/$', PaymentModeUpdateView.as_view(), name='payment_edit'),

     url(r'upload/location/$', LocationUploadView.as_view(), name='location_upload'),
    ]

credit/urls.py
from django.conf.urls import url

from credit.views import *

urlpatterns = [


      url(r'cm/list/(?P<cm>[\w]+)/$', CreditManagerAdminListView.as_view(), name="cm_admin_list"),
      url(r'cm/create/(?P<cm>[\w]+)/$', CreditManagerAdminCreateView.as_view(), name="cm_admin_create"),


      url(r'loan/list/$', LoanRequestListView.as_view(), name='loan_list'),
      url(r'loan/upload/$', LoanRequestUploadView.as_view(), name='loan_upload'),
      url(r'loan/repayment/logs/$', LoanRepaymentListView.as_view(), name='loan_repayment'),
      url(r'loan/(?P<pk>[\w]+)/$', LoanRequestDetailView.as_view(), name='loan_detail'),
      url(r'loan/repayment/(?P<pk>[\w]+)/$', LoanRepaymentFormView.as_view(), name='loan_repayment'),
      url(r'loan/edit/(?P<pk>[\w]+)/$', LoanRequestEdit.as_view(), name='loan_edit'),
      url(r'loan/delete/(?P<pk>[\w]+)/$', LoanRequestDeleteView.as_view(), name='loan_delete'),
      url(r'loan/approve/(?P<pk>[\w]+)/(?P<status>[\w]+)/$', ApproveLoan.as_view(), name='loan_approve'),

      url(r'loan/approval/(?P<pk>[\w]+)/$', ApproveLoanFormView.as_view(), name='approve_form'),

      url(r'loan/transaction/list/$', LoanTransactionListView.as_view(), name='loan_transaction_list'),

      url(r'list/$', CreditManagerListView.as_view(), name='cm_list'),
      url(r'create/$', CreditManagerCreateView.as_view(), name='cm_create'),
      url(r'edit/(?P<pk>[\w]+)/$', CreditManagerUpdateView.as_view(), name='cm_update'),

]

umis/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from conf import urls as conf_urls
from userprofile import urls as profile_urls
from product import urls as product_urls
from coop import urls as coop_urls 
from partner import urls as partner_urls
from operations import urls as op_urls
from endpoint import urls as ep_urls
from messaging import urls as msg_urls
from activity import urls as act_urls
from payment import urls as pay_urls
from credit import urls as credit_urls
from account import urls as account_urls
from dashboard.members import urls as member_insights_urls
from dashboard.members.views import *

from dashboard.views import *
from userprofile.views.authentication import LoginView, LogoutView
from conf.views import Handle404, Handle403

handler404 = Handle404.as_view()
handler403 = Handle403.as_view()

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^conf/', include(conf_urls, namespace='conf')),
    url(r'^profile/', include(profile_urls, namespace='profile')),
    url(r'^product/', include(product_urls, namespace='product')),
    url(r'^payment/', include(pay_urls, namespace='payment')),
    url(r'^coop/', include(coop_urls, namespace='coop')),
    url(r'^op/', include(op_urls, namespace='op')),
    url(r'^partner/', include(partner_urls, namespace='partner')),
    url(r'^endpoint/', include(ep_urls, namespace='endpoint')),
    url(r'^messaging/', include(msg_urls, namespace='messaging')),
    url(r'^activity/', include(act_urls, namespace='activity')),
    url(r'^credit/', include(credit_urls, namespace='credit')),
    url(r'^account/', include(account_urls, namespace='account')),
    url(r'^insights/', include(member_insights_urls, namespace='dashboard')),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^a_dashboard/$', AnalyticalDashboard.as_view(), name='a_dashboard'),
    url(r'^a_dashboard/get_members_per_month/$', get_members_per_month, name='get_members_per_month'),
    url(r'^a_dashboard/gender_distribution/$', gender_distribution, name='gender_distribution'),
    url(r'^a_dashboard/order_distribution/$', order_distribution, name='order_distribution'),
    url(r'^a_dashboard/get_orders_per_month/$', get_orders_per_month, name='get_orders_per_month'),
    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'member-dashboard/$', MemberAnalyticalDashboard.as_view(), name='member_dashboard'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credit/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from coop.models import CooperativeMember, MemberOrder, OrderItem
from django.contrib.auth.models import User


class CreditManager(models.Model):
    name = models.CharField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=120)
    contact_person = models.CharField(max_length=255, null=True, blank=True)
    contact_phone_number = models.CharField(max_length=255, null=True, blank=True)
    api_username = models.CharField(max_length=255, null=True, blank=True)
    api_password = models.CharField(max_length=255, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'credit_manager'

    def __unicode__(self):
        return "%s" % self.name


class CreditManagerAdmin(models.Model):
    user = models.OneToOneField(User, blank=True, related_name='cm_admin')
    credit_manager = models.ForeignKey(CreditManager, blank=True, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "%s" % self.user.get_full_name()


class LoanRequest(models.Model):
    reference = models.CharField(max_length=255, unique=True)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=255, null=True, blank=True)
    supplier = models.CharField(max_length=255, null=True, blank=True)
    credit_manager = models.ForeignKey(CreditManager, null=True, blank=True)
    requested_amount = models.DecimalField(max_digits=12, decimal_places=2)
    approved_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    amount_paid = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True, default=0)
    request_date = models.DateTimeField()
    order_item = models.ForeignKey(OrderItem, null=True, blank=True, on_delete=models.SET_NULL)
    deadline = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=64, choices=(('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'),
                                                      ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED'),
                                                      ('INPROGRESS', 'INPROGRESS'), ('PAID', 'PAID'), ('APPROVED', 'APPROVED')), default='PENDING')
    confirm_date = models.DateTimeField(null=True, blank=True)
    loan_reference = models.CharField(max_length=255, null=True, blank=True)
    paid_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    last_payment_date = models.DateTimeField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    response = models.TextField(null=True, blank=True)
    reject_reason = models.TextField(null=True, blank=True)
    loan_request_id = models.CharField(max_length=255, null=True, blank=True)
    agent = models.CharField(max_length=255, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'loan_request'

    def __unicode__(self):
        return "%s - %s | %s/-" % (self.member.get_name(), self.reference, self.approved_amount) or u''


class LoanTransaction(models.Model):
    reference = models.CharField(max_length=255, unique=True)
    member = models.ForeignKey(CooperativeMember, on_delete=models.CASCADE)
    credit_manager = models.ForeignKey(CreditManager, null=True, blank=True)
    amount = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    transaction_type = models.CharField(max_length=16, choices=(('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')))
    loan = models.ForeignKey(LoanRequest, null=True, blank=True)
    created_by = models.ForeignKey(User, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'loan_transaction'

    def __unicode__(self):
        return "%s" % self.member.get_name() or u''

class LoanRepaymentTransaction(models.Model):
    request = models.ForeignKey(LoanRequest, on_delete=models.CASCADE)
    amount_paid = models.DecimalField(max_digits=9, decimal_places=2)
    balance = models.DecimalField(max_digits=9, decimal_places=2, null=True, blank=True)
    repayment_date = models.DateTimeField()
    created_by = models.ForeignKey(User, null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'loan_repayment'

    def __unicode__(self):
        return "%s" % self.request.member.get_name() or u''

credit/forms.py
from django import forms
from django.contrib.auth.models import User
from credit.models import CreditManager, LoanRequest, LoanRepaymentTransaction
from conf.utils import bootstrapify, internationalize_number, PHONE_REGEX
from coop.models import CooperativeMember


class CreditManagerForm(forms.ModelForm):
    class Meta:
        model = CreditManager
        exclude = ['create_date', 'update_date']

class CreditManagerUserForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput)
    password = forms.CharField(max_length=150, required=True, widget=forms.PasswordInput)
    msisdn = forms.CharField(max_length=150)

    def __init__(self, *args, **kwargs):
        instance = kwargs.pop("instance", None)
        print(instance)
        super(CreditManagerUserForm, self).__init__(*args, **kwargs)
        if instance:
            self.fields.pop('password')
            self.fields.pop('confirm_password')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'msisdn', 'is_active', 'username', 'password',
                  'confirm_password']


class LoanUploadForm(forms.Form):
    sheetChoice = (
        ('1', 'sheet1'),
        ('2', 'sheet2'),
        ('3', 'sheet3'),
        ('4', 'sheet4'),
        ('5', 'sheet5'),
    )

    rowchoices = (
        ('1', 'Row 1'),
        ('2', 'Row 2'),
        ('3', 'Row 3'),
        ('4', 'Row 4'),
        ('5', 'Row 5')
    )

    choices = list()
    for i in range(65, 91):
        choices.append([i - 65, chr(i)])

    excel_file = forms.FileField()
    credit_manager = forms.ModelChoiceField(queryset=CreditManager.objects.all())
    proceed = forms.BooleanField(label='Proceed if farmer is not found', required=False)
    sheet = forms.ChoiceField(label="Sheet", choices=sheetChoice, widget=forms.Select(attrs={'class': 'form-control'}))
    row = forms.ChoiceField(label="Row", choices=rowchoices, widget=forms.Select(attrs={'class': 'form-control'}))
    name_col = forms.ChoiceField(label='Name Column', initial=0, choices=choices,
                                 widget=forms.Select(attrs={'class': 'form-control'}),
                                 help_text='The column containing the Last Name')
    phone_number_col = forms.ChoiceField(label='Phone Number Column', initial=1, choices=choices,
                                       widget=forms.Select(attrs={'class': 'form-control'}),
                                       help_text='The column containing the Phone Number Name')
    request_date_col = forms.ChoiceField(label='Request Date Column', initial=2, choices=choices,
                                      widget=forms.Select(attrs={'class': 'form-control'}),
                                      help_text='The column containing the Village')
    agent_col = forms.ChoiceField(label='Agent Column', initial=3, choices=choices,
                                        widget=forms.Select(attrs={'class': 'form-control'}),
                                        help_text='The column containing the Loan Agent')
    loan_amount_col = forms.ChoiceField(label='Loan Amount Column', initial=4, choices=choices,
                                     widget=forms.Select(attrs={'class': 'form-control'}),
                                     help_text='The column containing the Loan Amount')


class LoanSearchForm(forms.Form):
    search = forms.CharField(max_length=150, required=False)
    cooperative = forms.ChoiceField(widget=forms.Select(), choices=[], required=False)
    start_date = forms.CharField(max_length=150, required=False, widget=forms.TextInput(attrs={'id': 'uk_dp_start',
                                                                                               'data-uk-datepicker': "{format:'YYYY-MM-DD'}",
                                                                                               'autocomplete': "off"}))
    end_date = forms.CharField(max_length=150, required=False,
                               widget=forms.TextInput(attrs={'class': 'some_class', 'id': 'uk_dp_end',
                                                             'data-uk-datepicker': "{format:'YYYY-MM-DD'}",
                                                             'autocomplete': "off"}))
    status = forms.ChoiceField(widget=forms.Select(), required=False, choices=(('', '-----'), ('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'),
                                                      ('ACCEPTED', 'ACCEPTED'), ('NOT TAKEN', 'NOTTAKEN'),
                                                      ('INPROGRESS', 'INPROGRESS'), ('PAID', 'PAID'),
                                                      ('APPROVED', 'APPROVED')))

    def __init__(self,  *args, **kwargs):
        super(LoanSearchForm, self).__init__(*args, **kwargs)

        qs = LoanRequest.objects.values('member__cooperative__id', 'member__cooperative__name').distinct()
        print(qs)
        choices = [['', 'Cooperative']]
        for q in qs:
            choices.append([q['member__cooperative__id'], q['member__cooperative__name']])
        self.fields['cooperative'].choices = choices


class ApproveForm(forms.Form):
    amount = forms.IntegerField()
    supplier = forms.CharField(max_length=255)


class LoanRequestForm(forms.ModelForm):
    class Meta:
        model = LoanRequest
        exclude = ['create_date', 'update_date']

    def __init__(self, *args, **kwargs):
        super(LoanRequestForm, self).__init__(*args, **kwargs)
        self.fields['member'].queryset = CooperativeMember.objects.none()
        if self.instance.pk:
            cooperative = self.instance.member.id
            mbs = CooperativeMember.objects.filter(pk=cooperative)
            self.fields['member'].queryset = mbs


class LoanRepaymentForm(forms.ModelForm):
    class Meta:
        model = LoanRepaymentTransaction
        exclude = ['create_date', 'update_date']

    def __init__(self, *args, **kwargs):
        super(LoanRepaymentForm, self).__init__(*args, **kwargs)



bootstrapify(LoanRepaymentForm)
bootstrapify(LoanRequestForm)
bootstrapify(ApproveForm)
bootstrapify(LoanSearchForm)
bootstrapify(LoanUploadForm)
bootstrapify(CreditManagerForm)
bootstrapify(CreditManagerUserForm)

credit/templates/credit/creditmanager_list.html
{% extends 'base.html' %}
{% load static %}
{% load material_form %} 

{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Credit Institution List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            
           <a href="{% url 'credit:cm_create' %}" class="md-btn md-btn-success uk-float-right">Add Credit Institution</a>

        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Phone Number</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.name }}</td>
                                <td>{{ item.phone_number }}</td>
                                <td>
                                    <a href="{% url 'credit:cm_update' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Edit</a>
                                    <a href="{% url 'credit:cm_admin_list' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">Add Users</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- page specific plugins -->
    
    <script>
        $(function() {
            $(function() {
            // enable hires images
            altair_helpers.retina_images();
            // fastClick (touch devices)
            if(Modernizr.touch) {
                FastClick.attach(document.body);
            }
        });
        });
    </script>
{% endblock %}

credit/templates/credit/loanrequest_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load my_custom_tags %}

{% block page_content %}

<div class="uk-width-medium-8-10 uk-container-center reset-print">
<div class="uk-width-large-7-10 uk-row-first">
<div class="md-card md-card-single main-print" id="invoice" style="opacity: 1; transform: scale(1);">
    <div id="invoice_preview">
        <div class="md-card-toolbar">
            <div class="md-card-toolbar-actions hidden-print">
                <i class="md-icon material-icons" id="invoice_print"></i>
                <div class="md-card-dropdown" data-uk-dropdown="{pos:'bottom-right'}">
                    <i class="md-icon material-icons"></i>
                    <div class="uk-dropdown uk-dropdown-small">
                        <ul class="uk-nav">
                            <!--<li><a href="#">Archive</a></li>-->
                            <!--<li><a href="#" class="uk-text-danger">Remove</a></li>-->
                        </ul>
                    </div>
                </div>
            </div>
            <h3 class="md-card-toolbar-heading-text large" id="invoice_name">
                Reference {{ object.reference}}
            </h3>
        </div>
        <div class="md-card-content" style="">
            <div class="uk-margin-medium-bottom">
                <span class="uk-text-muted uk-text-small uk-text-italic">Date:</span> {{object.request_date|date:"Y M d"  }}
                <br>
                <!--<span class="uk-text-muted uk-text-small uk-text-italic">Due Date:</span> 02.01.2019-->
            </div>
            <div class="uk-grid uk-margin-large-bottom">
                <div class="uk-width-1-1">
                    <table class="uk-table">
                        <tbody>
                        <tr class="uk-table-middle">
                            <td>Reference</td><td>{{ object.refernce }}</td>
                        </tr>
                        <tr>
                            <td>Member Name</td><td>{{ object.member }}</td>
                            </tr>
                         <tr>
                            <td>Member National ID</td><td>{{ object.member.id_number }}</td>
                            </tr>
                        <tr>
                            <td>Member Phone Number</td><td>{{ object.member.phone_number }}</td>
                            </tr>
                        <tr>
                            <td>Cooperative</td><td>{{ object.member.cooperative }}</td>
                            </tr>
                         <tr>
                            <td>Supplier</td><td>{{ object.supplier }}</td>
                            </tr>
                        <tr>
                            <td>Request Date</td><td>{{ object.request_date }}</td>
                            </tr>
                        <tr>
                            <td>Status</td><td>{{ object.status }}</td>
                            </tr>

                        <tr>
                            <td>Request Amount</td><td>{{ object.requested_amount|default:""|intcomma }}</td>
                            </tr>
                        <tr>
                        <tr>
                            <td>Approved Amount</td><td>{{ object.approved_amount|default:""|intcomma }}</td>
                            </tr>
                        {% if object.status == 'APPROVED' %}
                        <tr>
                            <td>Amount Repaid</td><td>{{ object.amount_paid|default:""|intcomma }}</td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td>Provider Id</td><td>{{ object.loan_request_id|default:"" }}</td>
                            </tr>
                        <tr>
                            <td>Response</td><td>{{ object.response|safe }}</td>
                            </tr>
                        <tr>
                            <td>Agent</td><td>{{ object.agent|safe }}</td>
                            </tr>

                    </table>
                    <div class="buttons uk-text-right">
<!--                        <a href="{% url 'credit:loan_approve' pk=object.id status='STATUS' %}" class="md-btn md-btn-wave waves-effect waves-button md-btn-success">Check Status</a>-->
                        {% if object.status != "APPROVED" %}
                            <a href="{% url 'credit:approve_form' pk=object.id %}" class="md-btn md-btn-wave waves-effect waves-button md-btn-success">APPROVE</a>
                            <a href="{% url 'credit:loan_approve' pk=object.id status='NOTTAKEN' %}" class="md-btn md-btn-wave waves-effect waves-button md-btn-primary">NOT TAKEN</a>

<!--                            <a href="{% url 'credit:loan_approve' pk=object.id status='APPROVED' %}" class="md-btn md-btn-wave waves-effect waves-button md-btn-success">APPROVE</a>-->
                            <a href="{% url 'credit:loan_approve' pk=object.id status='REJECTED' %}" class="md-btn md-btn-wave waves-effect waves-button md-btn-danger">REJECT</a>
                        {% endif %}
                        {% if request.user.profile.is_credit_manager %}
                        {% endif %}
                        {% if object.status == "APPROVED" %}
                            <a href="{% url 'credit:loan_repayment' pk=object.id %}" class="md-btn md-btn-wave waves-effect waves-button md-btn-primary">RECORD REPAYMENT</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        </div>
    </div>
    <div id="invoice_form"></div>
</div>
</div>

</div>



{% endblock %}

credit/templates/credit/loanrequest_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load el_pagination_tags %}
{% load material_form %}
{% block style %}
<style type="text/css">
    .row-pagination{
        margin: 15px;
    }
    .row-pagination a{
        padding: 10px;
        border-radius: 4px;
    }

    .endless_page_current{
        background: #7cb342;
        color: #fff;
        padding: 10px;
        border-radius: 4px;
    }

</style>
{% endblock %}
{% block page_content %}
    <div class="uk-grid" data-uk-grid-margin>
        <div class="uk-width-medium-1-2">
            <h2 class="heading_a uk-margin-bottom">Loan Request List</h2>
        </div>
        <div class="uk-width-medium-1-2">
            
           <a href="{% url 'credit:cm_create' %}" class="md-btn md-btn-success uk-float-right">Add Credit Manager</a>
           <a href="{% url 'credit:loan_upload' %}" class="md-btn md-btn-success uk-float-right">Upload Loan</a>

        </div>
    </div>
    <div class="md-card uk-margin-medium-bottom">
        <div class="md-card-content">
            <div class="uk-overflow-container">
                <form class="" method="get">
                    <div class="uk-grid" data-uk-grid-margin>
                        {% for field in form %}
                            <div class="uk-width-medium-1-5">
                                {% include 'form/field.html' with field=field %}
                            </div>
                        {% endfor %}


                    </div>
                    <div class="uk-grid" data-uk-grid-margin>
                        <div class="uk-width-medium-4-5 uk-float-right">
                        </div>
                        <div class="uk-width-medium-1-5 uk-float-right">
                            <button class="md-btn" > Search </button>
                            <a href="." class="md-btn md-btn-small md-btn-flat md-btn-flat-primary uk-float-right uk-margin-small-left"><i class="material-icons md-24 " title="Delete">refresh</i></a>
                            <a  id="download_file" class="md-btn md-btn-success uk-float-right">Download Excel</a>
                        </div>
                     </div>
                </form>
                <table class="uk-table uk-table-striped">
                    <thead>
                    <tr>
                        <th>Reference</th>
                        <th>Member</th>
                        <th>Cooperative</th>
                        <th>Amount</th>
                        <th>Approved Amount</th>
                        <th>Request Date</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    {% paginate object_list %}{% get_pages %}
                        {% for item in object_list %}
                            <tr>
                                <td>{{ item.reference }}</td>
                                <td>{{ item.member }}</td>
                                <td>{{ item.member.cooperative }}</td>
                                <td>{{ item.requested_amount|intcomma }}</td>
                                <td>{{ item.approved_amount|default:""|intcomma }}</td>
                                <td>{{ item.request_date|date:"Y-m-d" }}</td>
                                <td>{{ item.status }}</td>

                                    <td>
                                        {% if request.user.profile.is_credit_manager or request.user.profile.is_union %}
                                        <a href="{% url 'credit:loan_edit' item.id %}" class="md-btn md-btn-warning waves-effect waves-button uk-float-right">EDIT</a>

                                            <a href="{% url 'credit:loan_detail' item.id %}" class="md-btn md-btn-wave waves-effect waves-button uk-float-right">OPEN</a>
                                        {% endif %}
                                        {% if request.user.is_superuser %}
                                            <a href="{% url 'credit:loan_delete' item.id %}" class="md-btn md-btn-danger waves-effect waves-button uk-float-right">DELETE</a>
                                        {% endif %}
                                    </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
             <div class="row-pagination">
                Showing entries
                {{ pages.current_start_index }}-{{ pages.current_end_index }} of
                {{ pages.total_count }}.
                {# Just print pages to render the Digg-style pagination. #}
                {% show_pages %}
            </div>
        </div>
    </div>
{% endblock %}
{% block page_specific_scripts %}
 <!-- page specific plugins -->

    <script>
        $('#download_file').on('click', function(){
            var url = window.location.href;
            sep = "?";

            if (url.indexOf('?') >= 0) {
                sep = "&";
            }
            window.location.href = url+sep+"download=true";
        });

        $(function() {
            $(function() {
            // enable hires images
            altair_helpers.retina_images();
            // fastClick (touch devices)
            if(Modernizr.touch) {
                FastClick.attach(document.body);
            }
        });
        });
    </script>
{% endblock %}